---
development:
  dialect: postgres
  database: {{envOr "POSTGRES_DB" "coredb"}}
  user: {{envOr "POSTGRES_USER" "admin"}}
  password: {{envOr "POSTGRES_PASSWORD" "password"}}
  host: {{envOr "POSTGRES_HOST" "database"}}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/core_test?sslmode=disable"}}

production:
  url: {{envOr "POSTGRES_URL" "postgres://postgres:postgres@127.0.0.1:5432/core_production?sslmode=disable"}}
